export const HARVESTER_MIN_COST =
  BODYPART_COST[MOVE] + BODYPART_COST[WORK] + BODYPART_COST[CARRY];
export const UPGRADER_MIN_COST =
  BODYPART_COST[MOVE] + BODYPART_COST[WORK] + BODYPART_COST[CARRY];
