version: "3"
services: 
  screeps:
    build: ./docker
    command: bash -c "if [ ! -d node_modules ]; then npm ci; fi && npm start"
    tty: true
    volumes:
      - .:/usr/src/app
    ports: 
      - 3000:3000